# Generated by Django 3.1.3 on 2020-12-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20201222_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='autor',
            new_name='user',
        ),
    ]
