# Generated by Django 3.1.3 on 2020-12-23 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_auto_20201223_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='user',
            new_name='autor',
        ),
    ]
