# Generated by Django 3.1.3 on 2020-12-23 15:34

from django.db import migrations, models
import slugify.slugify


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201223_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(auto_created=slugify.slugify.slugify, max_length=200, unique=True),
        ),
    ]
