# Generated by Django 3.1.3 on 2020-12-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabildos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrearCabildo',
            new_name='RegistroCabildos',
        ),
    ]
