# Generated by Django 3.1.3 on 2020-12-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabildos', '0002_auto_20201212_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroCabildos',
            new_name='RegistroCabildo',
        ),
    ]
