# Generated by Django 3.1.3 on 2020-12-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabildos', '0003_auto_20201212_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroCabildo',
            new_name='Cabildo',
        ),
    ]
