# Generated by Django 3.1.3 on 2020-12-12 22:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cabildos', '0004_auto_20201212_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabildo',
            name='categoria',
            field=models.CharField(choices=[('Valores', 'Valores'), ('Derechos', 'Derechos'), ('Deberes', 'Deberes'), ('Instituciones', 'Instituciones')], max_length=200, null=True, verbose_name='Categorias '),
        ),
        migrations.AlterField(
            model_name='cabildo',
            name='etiquetas',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cumplimiento de las leyes y normas', 'Cumplimiento de las leyes y normas'), ('Cumplimiento de obligaciones fiscales', 'Cumplimiento de obligaciones fiscales'), ('Cumplimiento de tratados y obligaciones internacionales', 'Cumplimiento de tratados y obligaciones internacionales'), ('De proteccion y conservacion de patrimonio historico y cultural', 'De proteccion y conservacion de patrimonio historico y cultural'), ('De satisfacer cargas publicas', 'De satisfacer cargas publicas'), ('Deber de transparencia en los actos de gobierno', 'Deber de transparencia en los actos de gobierno'), ('Deberes de proteccion de conservacion de la naturaleza', 'Deberes de proteccion de conservacion de la naturaleza'), ('Educacion civica', 'Educacion civica'), ('Ejercicio legitimo y no abusivo de los derechos', 'Ejercicio legitimo y no abusivo de los derechos'), ('Promocion de los derechos fundamentales', 'Promocion de los derechos fundamentales'), ('Proteccion, promocion y respeto de los derechos humanos y fundamentales', 'Proteccion, promocion y respeto de los derechos humanos y fundamentales'), ('Respeto de derechos de otros', 'Respeto de derechos de otros'), ('Respeto por la constitucion', 'Respeto por la constitucion'), ('Responsabilidad', 'Responsabilidad'), ('Responsabilidad civica', 'Responsabilidad civica'), ('Servicio a la comunidad', 'Servicio a la comunidad'), ('Unidad nacional y respeto por chile', 'Unidad nacional y respeto por chile'), ('Voto obligatorio', 'Voto obligatorio')], max_length=300),
        ),
        migrations.AlterField(
            model_name='cabildo',
            name='fecha',
            field=models.DateTimeField(verbose_name=' Fecha y hora  (aaaa,mm,dd) (hh,mm)'),
        ),
        migrations.AlterField(
            model_name='cabildo',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Link '),
        ),
        migrations.AlterField(
            model_name='cabildo',
            name='nombre',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre del Cabildo '),
        ),
    ]
