# Generated by Django 3.1.3 on 2020-12-13 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabildos', '0005_auto_20201212_1937'),
        ('cabildos', '0005_auto_20201212_1936'),
    ]

    operations = [
    ]
