# Generated by Django 3.1.3 on 2020-12-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabildos', '0011_auto_20201214_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabildo',
            old_name='conceptos',
            new_name='concepto',
        ),
    ]
