# Generated by Django 3.1.4 on 2020-12-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabildos', '0012_auto_20201214_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabildo_Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('hora', models.CharField(max_length=5)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
