# Generated by Django 3.1.3 on 2020-12-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabildos', '0013_auto_20201222_1059'),
        ('cabildos', '0013_cabildo_online'),
    ]

    operations = [
    ]
