# Generated by Django 3.1.4 on 2020-12-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabildos', '0013_cabildo_online'),
        ('cabildos', '0013_auto_20201222_1059'),
    ]

    operations = [
    ]
