# Generated by Django 3.1.4 on 2021-01-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabildos', '0014_merge_20201223_1214'),
        ('cabildos', '0014_merge_20201223_0856'),
    ]

    operations = [
    ]
