# Generated by Django 3.1.3 on 2021-01-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabildos', '0015_merge_20210102_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabildo_online',
            name='hora',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
