# Generated by Django 3.1.3 on 2021-01-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabildos', '0016_auto_20210112_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabildo_online',
            name='hora',
        ),
    ]
